// Generated by LiveScript 1.5.0
(function(){
  var bodyParser, server, ref$, convertForm, serializeForm;
  bodyParser = require('body-parser');
  server = require('express')();
  ref$ = require('./convert'), convertForm = ref$.convertForm, serializeForm = ref$.serializeForm;
  server.use(bodyParser.json({
    limit: '5mb'
  }));
  server.post('/convert', function(request, response){
    var ex;
    try {
      return serializeForm(response)(
      convertForm(
      request.body));
    } catch (e$) {
      ex = e$;
      response.statusCode = 400;
      response.write(ex.message);
      response.write('\n');
      response.write(ex.stack);
      return response.end();
    }
  });
  server.listen(8686);
}).call(this);
